# Prometheus ServiceMonitor to get application metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: uml-search-mcp-monitor
  namespace: mcp
  labels:
    app: uml-search-mcp 
spec:
  namespaceSelector:
    matchNames: 
      - mcp
  selector:
    matchLabels:
      app: uml-search-mcp
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 5s
      scrapeTimeout: 4s

